# -*- coding: utf-8 -*-
"""projract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8c8fW1n1epS8uGHtqX_gPBistesWKo3
"""

print("hello ")

"""# Gross pay using try and except (using handing)"""

#  Gross pay the using try and except Excaption handing

hour = input("enter the hour ")

try :
    hour = int(hour)
except :
  print("please enter the number")
  quit()

rate = input("enter the rate ")

try :
    rate = int(rate)
except ValueError:
  print("please enter the number")
  quit()

if hour < 40 :
  pay = hour * rate
else :
  pay = 40 * rate + (hour - 40) * rate * 1.5

print(pay)

#2 score checker

input_score = input("enter the score")

score = float(input_score)

if score >= 0.0 and score <= 1.0 :
  if score >= 0.9:
    print("A")
  elif score >= 0.8:
    print("B")
  elif score >= 0.7:
    print("C")
  elif score >= 0.6:
    print("D")
  else :
    print("F")
else :
  print("ERRORS")

#3 Leap year

year = int (input ("enter the year :"))

if year %4 ==0:
  if year %100 == 0:
    if year %400 == 0:
      print("leap year")
    else :
      print("not a leap year")

  else :
    print("leap year")
else :
  print("not a leap year")